// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rJFBt05al0m6F_vSJtqSu-Pz4nEoPos',
    appId: '1:118820860176:web:1b7fb0b066fc185f92b595',
    messagingSenderId: '118820860176',
    projectId: 'ryokou-7324',
    authDomain: 'ryokou-7324.firebaseapp.com',
    storageBucket: 'ryokou-7324.appspot.com',
    measurementId: 'G-HN1YDJ9D35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHucUBgnXJvyYTq1ABZWKyhrNQ_8KUmOs',
    appId: '1:118820860176:android:ead3fe97551509b192b595',
    messagingSenderId: '118820860176',
    projectId: 'ryokou-7324',
    storageBucket: 'ryokou-7324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRW_3CqAzonvONmOgECgz2xqPunBZCa4',
    appId: '1:118820860176:ios:028df3af79410d2e92b595',
    messagingSenderId: '118820860176',
    projectId: 'ryokou-7324',
    storageBucket: 'ryokou-7324.appspot.com',
    iosBundleId: 'com.example.ryokou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRW_3CqAzonvONmOgECgz2xqPunBZCa4',
    appId: '1:118820860176:ios:028df3af79410d2e92b595',
    messagingSenderId: '118820860176',
    projectId: 'ryokou-7324',
    storageBucket: 'ryokou-7324.appspot.com',
    iosBundleId: 'com.example.ryokou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9rJFBt05al0m6F_vSJtqSu-Pz4nEoPos',
    appId: '1:118820860176:web:111033bd076e11b492b595',
    messagingSenderId: '118820860176',
    projectId: 'ryokou-7324',
    authDomain: 'ryokou-7324.firebaseapp.com',
    storageBucket: 'ryokou-7324.appspot.com',
    measurementId: 'G-FXL1YJZTKB',
  );
}
